### PR TITLE
[misc] Using 'rate' instead of 'compensation'

### PR DESCRIPTION
**Pull request by evalica**
For
opensourcedesign/opensourcedesign.github.io#70 in order to align with
the naming used until now

### CODE REVIEW

**Comment by evalica** [comment]
@simonv3 can you please check this PR and see if something else is needed?

**Comment by evalica** [comment]
Also I had some problems in creating the PR because of the fork to belenbarrospena/opensrcdesignjobs . Is there something we can fix/simplify? Like deleting the initial repository or unlinking it somehow?

**Comment by evalica** [comment]
Related to https://github.com/opensourcedesign/jobs/commit/81fd77d3ad3f3cb73189145fe947839eeaab3840 since the website didn't displayed the rate.

**Comment by simonv3** [comment]
@evalica merged! good job catching the staticman update too. 

Were the issues you had with GitHub or locally?

**Comment by evalica** [comment]
@simonv3 the issues where with GitHub's desktop app, which created the PR for belen, instead of our fork (see https://github.com/belenbarrospena/opensrcdesignjobs/pull/2). Also in order to commit correctly I had to manually delete the upstream relation.

**Comment by simonv3** [comment]
Hmm, that might be because your original work was based on belen's branch?

**Comment by evalica** [comment]
Nope, my close was of opensourcedesign/opensrcdesignjobs

**Comment by simonv3** [comment]
:/. Yeah I'm afraid I don't know enough git to even know where to start looking into fixing this.

**Pull request merged**
