### PR TITLE
[Job submission form] Use the same width for form inputs

### PR DESCRIPTION
**Pull request by evalica**

### CODE REVIEW

**Comment by belenbarrospena** [comment]
No strong feelings about this, however, best practice is that input width should indicate expected input length. 

http://baymard.com/blog/form-field-usability-matching-user-expectations

Making all input fields the same width looks nicer, but does not communicate anything about the expected input. Not that we impose any limits on input width right now, though :)

**Comment by evalica** [comment]
Are there any recommended width's for particular inputs types like url's, or role, etc.?
My first reaction was that the entries had a variable width and it was a bug. 

While I truly agree that the input's size should suggest it's function, this classically applies to dates, card details, etc.

In our case I didn't understood why some inputs where longer than others, so that's why I felt the need to "fix" it :P

**Comment by belenbarrospena** [comment]
According to this dude

http://www.supermind.org/blog/740/average-length-of-a-url-part-2

the avergage url length is 76.97 characters. Mental what you find on the
internet :)

But this is probably heavily skewed towards the longer ranges, and in our
case the organisation url is likely to be the base domain and therefore
much shorter. So I don't think this is meaningful in any way.

In the version 2 of the form, the only "irregular" fields are the ones in
the "about you" section (organisation and organisation url) and the payment
info that we show when you select "paid" in "Contribution". All others are
the same width. The name of the organisation is bound to be shorter than
its url, and a figure or a range are also bound to be shorter than the
surrounding text areas.

So why not leaving as is? Was this version of the form where you wondered
about the input lenghts? Or was it the first one?

In any case, this is a tiny issue: really not worth losing much sleep over
it. So I'll merge.

Thanks!

**Comment by belenbarrospena** [comment]
Sorry @simonv3 Didn't mean to step on your toes. When I merged this I thought the PR was on my branch, not the "real" branch. Sometimes GitHub is confusing :/ 

Feel free to roll it back if you disagree :)

**Comment by simonv3** [comment]
Branching is confusing - you definitely didn't step on my toes! I made it on the OSD org so everyone could contribute :)

**Pull request merged**
